name : Golang web example
on:
    push:
        branches:
        - 'v1.0'
        tags:
        - 'latest'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "latest"
          force_push_tag: true
          message: "Latest release"
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          tag: "latest"
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "body.md"

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Get Repository URL
        id: repo_url
        run: echo "::set-output name=url::https://github.com/${{ github.repository }}"

      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        post-actions:
          - name: Extract Railway Deployment URL
            id: deployment_url
            run: |
              DEPLOYMENT_URL=$(railway status | grep "Deployment URL" | awk '{print $3}')
              echo "::set-output name=url::$DEPLOYMENT_URL"

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
              {
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "DipSA41C CI/CD Assignment Submission"
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Name:*\nXu Zihang\n\n*Matriculation:*\nA0276820B\n\n*Email:*\nE1133135@u.nus.edu\n\n*Repository:*\n$${{ steps.repo_url.outputs.url }}"
                    }
                  },
                  {
                    "type": "section",
                    "block_id": "section789",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Deployment:*\n<$${{ steps.deployment_url.outputs.url }}/> \n<$${{ steps.deployment_url.outputs.url }}|Open application>"
                      }
                    ]
                  }
                ]
              }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK